"""test2

Revision ID: e2cd0808cd26
Revises: 5ac803eb3d1e
Create Date: 2024-03-20 13:53:57.141185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2cd0808cd26'
down_revision: Union[str, None] = '5ac803eb3d1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_token_token_key', 'user_token', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_token_token_key', 'user_token', ['token'])
    # ### end Alembic commands ###
